version: '3'

# expansions: 3
# To be done

vars:
    PWD:
        sh: pwd
    TAG:
        sh: git describe --tags
    VERSION: "{{or .BUILD_VERSION .TAG}}"
    DATE: 
        sh: date +%FT%TZ%z
    BUILD_DIR: "{{ .PWD }}/build"
    
tasks:
    clean:
        cmds:
            - go clean
            - rm -rf "{{ .BUILD_DIR }}"
    test:
        cmds:
            - go test ./... -race -count=1
    lint:
        cmds:
            - golangci-lint run
    hkcam:
        cmds:
            - "go build -o {{ .BUILD_DIR }}/hkcam -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go"
            - "{{ .BUILD_DIR }}/hkcam --verbose --port={{ .PORT }} --data_dir=cmd/hkcam/db"
        vars:
            LDFLAGS: "\"-X main.Version={{ .VERSION }} -X main.Date={{ .DATE }}\""
            PORT: '{{ default "8080" .PORT }}'
        sources:
            - Taskfile.yml
    pack:
        cmds:
            # Raspberry Pi
            - "GOOS=linux GOARCH=arm GOARM=6 go build -o {{ .BUILD_DIR }}/{{ .PACKAGE_RPI }}/{{ .BINARY }} -ldflags {{ .LDFLAGS }} cmd/hkcam/main.go cmd/hkcam/fs.go"

            - "tar -cvzf {{ .PACKAGE_RPI }}.tar.gz -C {{ .BUILD_DIR }}/{{ .PACKAGE_RPI }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_LINUX_64 }}.tar.gz -C {{ .BUILD_DIR }}/{{ .PACKAGE_LINUX_64 }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_LINUX_32 }}.tar.gz -C {{ .BUILD_DIR }}/{{ .PACKAGE_LINUX_32 }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_INTEL_MAC }}.tar.gz -C {{ .BUILD_DIR }}/{{ .PACKAGE_INTEL_MAC }} {{ .BINARY }}"
            - "tar -cvzf {{ .PACKAGE_M1_MAC }}.tar.gz -C {{ .BUILD_DIR }}/{{ .PACKAGE_M1_MAC }} {{ .BINARY }}"
        vars:
            BINARY: hkcam
            PACKAGE_RPI: "{{ .BINARY }}-{{ .VERSION }}_linux_arm"
            LDFLAGS: "\"-X main.Version={{ .VERSION }} -X main.Date={{ .DATE }}\""